#!/usr/bin/env bash

# docker build --file ./build/Dockerfile.alpine -t concurry-alpine .
# ID=$(docker create concurry-alpine)  # returns container ID
# docker cp $ID:/worker/dist/concurry-arch ./dist/concurry-arch
# docker rm $ID

docker build --file ./build/Dockerfile.alpine -t concurry-alpine .
ID=$(docker create concurry-alpine)  # returns container ID
docker cp $ID:/worker/dist/concurry-arch ./dist/concurry-arch
docker rm $ID
